name: CI
on:
  push:
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
      - ".gitignore"
      - "CODEOWNERS"
      - "renovate.json"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
      - ".gitignore"
      - "CODEOWNERS"
      - "renovate.json"

jobs:
  build:
    name: Build and test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          cache: true
          go-version-file: go.mod
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
