name: CI
on:
  push:
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
      - ".gitignore"
      - "CODEOWNERS"
      - "renovate.json"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
      - ".gitignore"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Use cache
        uses: ./.github/actions/go-cache
        with:
          cache-ver: v1
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
