name: Lint markdown
on:
  push:
    branches:
      - master
    paths:
      - "**/*.md"
  pull_request:
    branches:
      - master
    paths:
      - "**/*.md"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actionshub/markdownlint@2.0.2
