name: Lint markdown
on:
  push:
    branches:
      - master
    paths:
      - "**/*.md"
  pull_request:
    branches:
      - master
    paths:
      - "**/*.md"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xt0rted/markdownlint-problem-matcher@v1
      - run: markdownlint **/*.md --ignore node_modules
