name: release
on:
  workflow_dispatch:
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Git as GitHub Actions Bot
        uses: Lucky3028/git-as-gha@v1.0.0
      - name: Install standard-version
        run: npm install -g standard-version@v9.3.2
      - name: Generate changelog
        run: standard-version
      - name: Push tag
        run: git push origin --tags
      - name: Upload CHANGELOG.md
        uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: CHANGELOG.md
  goreleaser:
    runs-on: ubuntu-latest
    needs:
      - changelog
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download CHANGELOG.md
        uses: actions/download-artifact@v3
        with:
          name: changelog
      # ここでpullし直さないと、前のjobでのタグを読み込まない
      - run: git pull origin ${GITHUB_REF#refs/heads/}
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Import GPG key
        id: import_gpg
        uses: hashicorp/ghaction-import-gpg@v2.1.0
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.GPG_KEY_PASSPHRASE }}
      - name: Git as GitHub Actions Bot
        uses: Lucky3028/git-as-gha@v1.0.0
      - name: Use cache
        uses: ./.github/actions/go-cache
        with:
          cache-ver: v1
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --release-notes CHANGELOG.md
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
